# Pandoc --defaults for HTML output.
# Load on top of common defaults.
to: html5
template: config/pandoc/templates/default.html5
include-after-body:
- config/pandoc/themes/default.html
- config/pandoc/plugins/core.html # needed for all first-party plugins
- config/pandoc/plugins/accordion.html
- config/pandoc/plugins/anchors.html
- config/pandoc/plugins/attributes.html
- config/pandoc/plugins/jump-to-first.html
- config/pandoc/plugins/lightbox.html
- config/pandoc/plugins/link-highlight.html
- config/pandoc/plugins/table-of-contents.html
- config/pandoc/plugins/tooltips.html
- config/pandoc/plugins/analytics.html
- config/pandoc/plugins/mathjax.html
filters:
- config/pandoc/filters/links.lua
variables:
  document-css: false
  math: ""
html-math-method:
  method: mathjax