# Pandoc --defaults for HTML proposal output.
# Load on top of common defaults and html defaults.
include-after-body:
- config/pandoc/plugins/hypothesis.html
- config/pandoc/plugins/canonical-link.html