# Pandoc --defaults for HTML output.
# Load on top of common defaults.
to: html5
output-file: output/manuscript.html
# include-before-body:
### third-party plugins
#- build/plugins/d3.html
include-after-body:
### theme
- config/themes/default.html
### first-party plugins
- config/plugins/core.html # needed for all first-party plugins
- config/plugins/accordion.html
- config/plugins/anchors.html
- config/plugins/attributes.html
#- config/plugins/inline-svg.html
- config/plugins/jump-to-first.html
- config/plugins/lightbox.html
- config/plugins/link-highlight.html
- config/plugins/table-of-contents.html
- config/plugins/tooltips.html
### third-party plugins
- config/plugins/analytics.html
- config/plugins/hypothesis.html
- config/plugins/mathjax.html
#- config/plugins/scite.html
variables:
  document-css: false
  math: ""
html-math-method:
  method: mathjax