# Pandoc --defaults for HTML output.
# Load on top of common defaults.
to: html5
template: config/pandoc/templates/default.html5
include-after-body:
- config/themes/default.html
- config/plugins/core.html # needed for all first-party plugins
- config/plugins/accordion.html
- config/plugins/anchors.html
- config/plugins/attributes.html
- config/plugins/jump-to-first.html
- config/plugins/lightbox.html
- config/plugins/link-highlight.html
- config/plugins/table-of-contents.html
- config/plugins/tooltips.html
- config/plugins/analytics.html
- config/plugins/mathjax.html
- config/plugins/acp-header.html
filters:
- config/pandoc/filters/links.lua
variables:
  document-css: false
  math: ""
html-math-method:
  method: mathjax