name: Deploy GitHub Pages - pull request

on:
  pull_request:
    branches: [ "master" ]

jobs:
  deploy-gh-pages-pr:
    runs-on: ubuntu-latest
    name: Download acp-site bundle
    steps:
      - name: '📥 Checkout Code'
        uses: actions/checkout@v2.3.4
      - name: '❄ Install Nix'
        uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-21.05
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://cache.nixos.org/
      - name: '🧱 Build'
        id: build
        run: |
          export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')

          nix-build release.nix -A acp-site-tarball -o acp-site-tarball --argstr urlPrefix "/acp/pull-requests/${PR_NUMBER}"
      - name: '📤 Publish ACP site'
        run: |
          echo "Checking out gh-pages branch..."
          git config --local user.email "samuel.evans-powell@iohk.io"
          git config --local user.name ${{ github.actor }}
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages

          export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          export FOLDER_NAME="pull-requests/${PR_NUMBER}"
          export TMP_FOLDER_NAME="pull-requests/${PR_NUMBER}-tmp"

          echo "Extracting site tarball for PR #${PR_NUMBER}..."
          mkdir -p "${TMP_FOLDER_NAME}"
          tar -xzvf acp-site-tarball/acp-site.tar.gz --directory "${TMP_FOLDER_NAME}"
          rm -rf "${FOLDER_NAME}"
          mv "${TMP_FOLDER_NAME}" "${FOLDER_NAME}"
          rm acp-site-tarball

          echo "Committing changes..."
          git add -A
          git commit -m "Deployed PR#${PR_NUMBER}" || true
          git push https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git HEAD:gh-pages
      - name: '📢 Notify contributors'
        uses: actions/github-script@v5
        with:
          script: |
            var msg = `🚢 Your pull request will be deployed [here](https://${context.repo.owner}.github.io/${context.repo.repo}/pull-requests/${context.issue.number}/index.html) soon.

            Check the status of the deploy [here](https://github.com/${context.repo.owner}/${context.repo.repo}/deployments/activity_log?environment=github-pages).`

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })